### ISSUE TITLE
What is in zen2 build?

### ISSUE THREAD

**Issue by joinsplit** [fabianishere/pve-edge-kernel#10]
Hi,

I was interested to know what specific fixes you have in for your zen2 kernel build? I am whether I see an improvement on my node using the latest 5.8.7 zen2 build vs the standard build.

Thanks.

**Comment by fabianishere** [comment]
Hi,

The Zen 2 builds are identical in configuration to the regular builds, except that they are built specifically for Zen 2 machines (by enabling  `-march=znver2`). This might lead to some microarchitectural optimizations possibly resulting in a faster kernel, though the difference may not be a lot depending on the workload.
