### ISSUE TITLE
Add Linux 5.12 builds

### ISSUE THREAD

**Issue by amoiseiev** [fabianishere/pve-edge-kernel#105]
It looks like 5.11 is now EOL. What are you thoughts on jumping to 5.12? 

I built it for my systems with the latest ZFS 2.1.0-rc5. 

So far, it appears to be functional:

root@pve-bfs-1:~# uname -a
Linux pve-bfs-1 5.12.6-1-edge #1 SMP 5.12.6-1-edge (Wed, 19 May 2021 12:10:07 +0000) x86_64 GNU/Linux

# dmesg | grep -i zfs
[    6.037061] ZFS: Loaded module v2.1.0-rc5, ZFS pool version 5000, ZFS filesystem version 5

root@pve-bfs-1:~# modinfo zfs | grep -i version
version:        2.1.0-rc5
srcversion:     18176EA5C58E37536B4B6C2
vermagic:       5.12.6-1-edge SMP mod_unload modversions 

# zfs list
NAME       USED  AVAIL     REFER  MOUNTPOINT
zfs-test   420K   860G       96K  /zfs-test

Other things tested: PCI passthrough, pmem passthough. ceph, corosync clustering, Mellanox NICs.

**Comment by fabianishere** [comment]
I was waiting for ZFS to support Linux 5.12, but it seems like it can compile now on Linux 5.12.

**Comment by amoiseiev** [comment]
> I was waiting for ZFS to support Linux 5.12, but it seems like it can compile now on Linux 5.12.

I believe 2.1.0-rc5 is the first version with official 5.12 support

**Comment by fabianishere** [comment]
Linux 5.12 builds are now included with #106 and #107. Let me know if they work for you.
