### ISSUE TITLE
Submodule fetch for ZFS breaks on missing commit hash

### ISSUE THREAD

**Issue by appleguy** [fabianishere/pve-edge-kernel#11]
Thanks for the incredibly useful project — it's greatly appreciated!

`Fetched in submodule path 'submodules/zfsonlinux/upstream', but it did not contain 6b18d7df3772cffa6469b00866d7eae585b912ae. Direct fetching of that commit failed.`

After first trying a week ago, I'm continuing to see this error when fetching submodules. What's the recommended workaround?

**Comment by appleguy** [comment]
Here's a more complete log:

`root@C246:~/Downloads/Linux/pve-edge-kernel# git submodule update --init --recursive --depth 1
Submodule 'submodules/ubuntu-mainline' (git://git.launchpad.net/~ubuntu-kernel-test/ubuntu/+source/linux/+git/mainline-crack) registered for path 'submodules/ubuntu-mainline'
Submodule 'submodules/zfsonlinux' (git://git.proxmox.com/git/zfsonlinux.git) registered for path 'submodules/zfsonlinux'
Cloning into '/root/Downloads/Linux/pve-edge-kernel/submodules/ubuntu-mainline'...
Cloning into '/root/Downloads/Linux/pve-edge-kernel/submodules/zfsonlinux'...
remote: Total 0 (delta 0), reused 0 (delta 0)
remote: Enumerating objects: 9251, done.
remote: Counting objects: 100% (9251/9251), done.
remote: Compressing objects: 100% (4725/4725), done.
remote: Total 5001 (delta 4125), reused 774 (delta 149)
Receiving objects: 100% (5001/5001), 2.66 MiB | 4.71 MiB/s, done.
Resolving deltas: 100% (4125/4125), completed with 3934 local objects.
From git://git.launchpad.net/~ubuntu-kernel-test/ubuntu/+source/linux/+git/mainline-crack
 * branch                2fbac55619813a5702ce040a3f84e194fb5d7bd8 -> FETCH_HEAD
Submodule path 'submodules/ubuntu-mainline': checked out '2fbac55619813a5702ce040a3f84e194fb5d7bd8'
Submodule path 'submodules/zfsonlinux': checked out '38e2c8078f63f952e3b24ec2057c7c389543ecb2'
Submodule 'zfs/upstream' (git://git.proxmox.com/git/mirror_zfs) registered for path 'submodules/zfsonlinux/upstream'
Cloning into '/root/Downloads/Linux/pve-edge-kernel/submodules/zfsonlinux/upstream'...
remote: Total 0 (delta 0), reused 0 (delta 0)
fatal: the remote end hung up unexpectedly
Fetched in submodule path 'submodules/zfsonlinux/upstream', but it did not contain 6b18d7df3772cffa6469b00866d7eae585b912ae. Direct fetching of that commit failed.
Failed to recurse into submodule path 'submodules/zfsonlinux'
root@C246:~/Downloads/Linux/pve-edge-kernel# cd submodules/zfsonlinux/
root@C246:~/Downloads/Linux/pve-edge-kernel/submodules/zfsonlinux# ls
debian	Makefile  README  upstream
root@C246:~/Downloads/Linux/pve-edge-kernel/submodules/zfsonlinux# git branch
* (HEAD detached at 38e2c80)
  master
root@C246:~/Downloads/Linux/pve-edge-kernel/submodules/zfsonlinux# git tag
root@C246:~/Downloads/Linux/pve-edge-kernel/submodules/zfsonlinux# cd upstream
root@C246:~/Downloads/Linux/pve-edge-kernel/submodules/zfsonlinux/upstream# git branch
* master
root@C246:~/Downloads/Linux/pve-edge-kernel/submodules/zfsonlinux# git tag
root@C246:~/Downloads/Linux/pve-edge-kernel/submodules/zfsonlinux/upstream# git log
commit afc8f0a6ffb4dd2dd5e17abc39e035eb7c7bcdc8 (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: Ryan Moeller <ryan@freqlabs.com>
Date:   Wed Sep 18 12:05:57 2019 -0400

    Refactor libzfs_error_init newlines
    
    Move the trailing newlines from the error message strings to the format
    strings to more closely match the other error messages.
    
    Reviewed-by: Brian Behlendorf <behlendorf1@llnl.gov>
    Reviewed-by: George Melikov <mail@gmelikov.ru>
    Signed-off-by: Ryan Moeller <ryan@ixsystems.com>
    Closes #9330
`

**Comment by fabianishere** [comment]
Hi,

Thanks for the appreciation! :)

I can reproduce this issue locally: I suspect it is related to performing a shallow fetch.

**Comment by fabianishere** [comment]
It seems that you get this error if you perform a shallow recursive fetch of all submodules. What works for me currently:

```shell
git clone git@github.com:fabianishere/pve-edge-kernel.git
git submodule update --init --depth=1 --recursive submodules/ubuntu-mainline
git submodule update --init --recursive submodules/zfsonlinux
```

**Comment by appleguy** [comment]
Interesting, this makes sense. Thanks a lot for the fix!

**Comment by appleguy** [comment]
Sure enough, this works great! Feel free to update the README and close out.

(I did need to use `git clone https://github.com/fabianishere/pve-edge-kernel` though, as the github@ one requires a cert).

**Comment by fabianishere** [comment]
Great! I have updated the README as well.

**Comment by appleguy** [comment]
You're so fast! Funny enough, it looks like there is a build issue; I did `apt install dwarves`, but it's version 1.12-2 instead of the required >1.16.

I should be able to fix this no problem, but wanted to let you know in case it's news.

```make PVE_BUILD_FLAVOR="zen" PVE_BUILD_CFLAGS="-march=native"
Using build flavor: zen
cd build; dpkg-buildpackage --jobs=auto -b -uc -us
dpkg-buildpackage: info: source package pve-edge-kernel
dpkg-buildpackage: info: source version 5.8.0-1
dpkg-buildpackage: info: source distribution edge
dpkg-buildpackage: info: source changed by Fabian Mastenbroek <mail.fabianm@gmail.com>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build .
dpkg-checkbuilddeps: error: Unmet build dependencies: dwarves (>= 1.16)
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
make: *** [Makefile:88: pve-edge-kernel-5.8.0-1-zen_5.8.0-1_amd64.deb] Error 3```

**Comment by fabianishere** [comment]
Thank you for reporting, I am aware of it, however dwarves >= 1.16 is unfortunately currently only in the Debian testing repositories, so this step requires some manual installation.

I'll add some more information in the README about this issue.

**Comment by appleguy** [comment]
Sounds good; this worked fine for me:

```
wget http://ftp.us.debian.org/debian/pool/main/d/dwarves-dfsg/dwarves_1.17-1_amd64.deb
apt install ./dwarves_1.17-1_amd64.deb
```

**Comment by fabianishere** [comment]
That was my approach as well. If you want to make it even more complicated, you can add Debian Testing to your repositories and lower its priority.
