### ISSUE TITLE
Automatic update script

### ISSUE THREAD

**Issue by pkejval** [fabianishere/pve-edge-kernel#12]
Hello I created simple update script for unattended updates from cron. I am aware that automatic updates of custom build kernel aren't the best idea for hypervisor but I hope someone will find it useful.

You can see it here https://gist.github.com/pkejval/3c5a2dce94080185a05de6c08508ba04

**Comment by Servery** [comment]
I had to `apt install jq`. Your script works perfectly. Thanks. ;-)

**Comment by pkejval** [comment]
Thanks. But it has some problems right now. I am working on update.

**Comment by juliokele** [comment]
https://gist.github.com/juliokele/8c3e249d9f32ea09545d303f983cdedb#gistcomment-3666921

> Thanks. But it has some problems right now. I am working on update.
> 
> EDIT: Updated gist with new version which should fix new version detection.

Version checking fixed:
https://gist.github.com/juliokele/8c3e249d9f32ea09545d303f983cdedb

**Comment by chchia** [comment]
thank you, this is working well.

**Comment by DjSni** [comment]
hmm, wouldn't a repo be easier for everyone ?!

**Comment by fabianishere** [comment]
@DjSni Yes, definitely! However, I don’t have the resources to host an APT repository for this at the moment. I am waiting for some SaaS services (APT on Github Packages?) to become available 😄

**Comment by pkejval** [comment]
Can this be helpful? https://github.com/rpatterson/github-apt-repos

**Comment by fabianishere** [comment]
I am looking now into [CloudSmith](https://cloudsmith.com) to see if we can work with it.

**Comment by fabianishere** [comment]
Have a look at the README for instructions on installing kernels via the Debian repository.

**Comment by DjSni** [comment]
Just tried it and goes without problems! But think a kind of stable channel would be even better... Like 'apt install pve-kernel-sable' but only if it is not too much work...

**Comment by fabianishere** [comment]
@DjSni What do you mean by stable channel? You can already track the stable or longterm kernels by installing `pve-kernel-5.12-edge` and `pve-kernel-5.10-edge` respectively.

**Comment by DjSni** [comment]
a kind of virtual package, `pve-kernel-stable` references e.g. the current `pve-kernel-5.12` as soon as this is no longer stable the sable package `pve-kernel-stable` remains the same but then references e.g. `pve-kernel-5.13` or `pve-kernel-5.14`.
