### ISSUE TITLE
I can't seem to get this to package

### ISSUE THREAD

**Issue by Xaekai** [fabianishere/pve-edge-kernel#144]
Hello, I am having difficulties following the manual build process. I've tried this now in the following scenarios: Directly on my Proxmox host (Debian 11), a Debian 10 CT, an Ubuntu 21 CT, and a Debian 11 CT.

The result is always the same, the process ends here
```
  ...
  HDRINST usr/include/asm/fcntl.h
  HDRINST usr/include/asm/termios.h
  HDRINST usr/include/asm/ipcbuf.h
  HDRINST usr/include/asm/socket.h
  HDRINST usr/include/asm/termbits.h
  HDRINST usr/include/asm/unistd_32.h
  INSTALL /home/xaekai/src/pve-edge-kernel/debian/pve-kernel-libc-dev/usr/include
make[2]: Leaving directory '/home/xaekai/src/pve-edge-kernel/linux'
rm -rf debian/pve-kernel-libc-dev/usr/include/drm debian/pve-kernel-libc-dev/usr/include/scsi
find debian/pve-kernel-libc-dev/usr/include \( -name .install -o -name ..install.cmd \) -execdir rm {} +
# Move include/asm to arch-specific directory
mkdir -p debian/pve-kernel-libc-dev/usr/include/x86_64-linux-gnu
mv debian/pve-kernel-libc-dev/usr/include/asm debian/pve-kernel-libc-dev/usr/include/x86_64-linux-gnu/
test ! -d debian/pve-kernel-libc-dev/usr/include/arch || \
        mv debian/pve-kernel-libc-dev/usr/include/arch debian/pve-kernel-libc-dev/usr/include/x86_64-linux-gnu/
touch .usr_headers_install_mark
make[1]: Leaving directory '/home/xaekai/src/pve-edge-kernel'
make: *** [debian/rules:16: binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui --jobs=auto -b failed
```
That "Line 1182"  Of what? Some virtually compiled script that only exists during execution? Not helpful. It's been a few years since I was intimately familiar with deb packaging, so I'm out of my depth here.

The steps I took to get here this last time:
1.) Create fresh Debian 11 CT
2.) Login root through Proxmox console, confirm network, install sudoers and openssh, setup regular user with sudo
3.) Shell in from regular terminal
4.) Run these commands
```
sudo apt update
sudo apt upgrade
sudo apt install devscripts debhelper equivs git
mkdir src
cd src
git clone https://github.com/fabianishere/pve-edge-kernel
cd pve-edge-kernel
git checkout v5.13.5-1 
git submodule update --init --depth=1 --recursive linux
git submodule update --init --recursive
debian/rules debian/control
sudo mk-build-deps -i
export PVE_KERNEL_CFLAGS="-march=znver2"
debuild -ePVE* --jobs=auto -b -uc -us
```

What am I doing wrong?

**Comment by fabianishere** [comment]
Hi, could you share your full build log?

**Comment by Xaekai** [comment]
Should I just redirect debuild output to a file for that?

**Comment by fabianishere** [comment]
Yes, I think that would be the easiest approach.

**Comment by Xaekai** [comment]
The outout of `debuild -ePVE* --jobs=auto -b -uc -us > /tmp/build.log` is available [here](https://gist.githubusercontent.com/Xaekai/6d8e1960e94cfdb38ce70e283270b421/raw/df430b61bfb61ef3be86d414b3b00596ce18af83/build.log)

I neglected to redirect stderr to stdout, but the only thing to come out of that was this, at the very end, just as before.
```
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui --jobs=auto -b failed
```

**Comment by fabianishere** [comment]
It seems like this is the issue:
> make[2]: Leaving directory '/home/xaekai/src/pve-edge-kernel/linux'
/usr/bin/make -C linux headers_install ARCH=x86 INSTALL_HDR_PATH='/home/xaekai/src/pve-edge-kernel'/debian/pve-kernel-libc-dev/usr
make[2]: Entering directory '/home/xaekai/src/pve-edge-kernel/linux'
Makefile.config:238: *** Please set 'PYTHON' appropriately.  Stop.
make[3]: *** [Makefile.perf:238: sub-make] Error 2
make[2]: *** [Makefile:70: all] Error 2
make[2]: Leaving directory '/home/xaekai/src/pve-edge-kernel/linux/tools/perf'
dh_auto_build: error: cd linux/tools/perf && make -j28 "INSTALL=install --strip-program=true" prefix=/usr HAVE_NO_LIBBFD=1 HAVE_CPLUS_DEMANGLE_SUPPORT=1 NO_LIBPYTHON=1 NO_LIBPERL=1 NO_LIBCRYPTO=1 PYTHON=python2.7 returned exit code 2
  HOSTCC  scripts/unifdef
make[1]: *** [debian/rules:137: .tools_compile_mark] Error 25
make[1]: *** Waiting for unfinished jobs....

Could you pull the `v5.13.x` branch again and check whether 8f5f279 fixes your issue.

**Comment by Xaekai** [comment]
```sh
xaekai@deb11packager:~/src$ cd ..
xaekai@deb11packager:~/src$ ls *.deb -l
-rw-r--r-- 1 xaekai xaekai  1610244 Jul 27 17:36 linux-tools-5.13_5.13.5-1_amd64.deb
-rw-r--r-- 1 xaekai xaekai  5927540 Jul 27 17:36 linux-tools-5.13-dbgsym_5.13.5-1_amd64.deb
-rw-r--r-- 1 xaekai xaekai 10328396 Jul 27 17:36 pve-headers-5.13.5-1-edge_5.13.5-1_amd64.deb
-rw-r--r-- 1 xaekai xaekai    18980 Jul 27 17:36 pve-headers-5.13.5-1-edge-dbgsym_5.13.5-1_amd64.deb
-rw-r--r-- 1 xaekai xaekai     5432 Jul 27 17:36 pve-headers-5.13-edge_5.13.5-1_all.deb
-rw-r--r-- 1 xaekai xaekai 65173136 Jul 27 17:36 pve-kernel-5.13.5-1-edge_5.13.5-1_amd64.deb
-rw-r--r-- 1 xaekai xaekai     5428 Jul 27 17:36 pve-kernel-5.13-edge_5.13.5-1_all.deb
-rw-r--r-- 1 xaekai xaekai  1071708 Jul 27 17:36 pve-kernel-libc-dev_5.13.5-1_amd64.deb
```

Frabjous. Thank you. https://github.com/fabianishere/pve-edge-kernel/commit/8f5f2792ef500e9bf926670118d6bc72806efc9c does indeed resolve my issue. Closing.
