### ISSUE TITLE
5.13.14 and 5.14 kernels won't boot on systems with NVDIMM

### ISSUE THREAD

**Issue by amoiseiev** [fabianishere/pve-edge-kernel#164]
5.13.14 and 5.14 kernels won't boot on systems with NVDIMM due to UBSAN and NFIT module issues. 

The issue is likely not specific to NVDIMM or NFIT and may appear in variety of different configs.

The solution in my case is to either remove Intel Optane P100 memory from the servers or disable UBSAN. 

More info: 

https://github.com/torvalds/linux/blob/master/lib/Kconfig.ubsan#L23

and my report to Ubuntu's kernel team: 

https://lists.ubuntu.com/archives/kernel-team/2021-September/123828.html

**Comment by fabianishere** [comment]
Resolved for both 5.14.x and 5.13.x now. You can download the updated kernels from the Cloudsmith repo or here on Github.
