### ISSUE TITLE
How Can I use make menuconfig to add PPP(point-to-point protocol) support?

### ISSUE THREAD

**Issue by Miroxyz** [fabianishere/pve-edge-kernel#194]
I want to build the kernel with PPP(point-to-point protocol) support. But I found that the `make menuconfig` cannot be used.

**Comment by fabianishere** [comment]
PPP is already included by default in both the official kernels and the kernels from this repository. See any of `/boot/config-*`:

```
CONFIG_PPP=y
CONFIG_PPP_BSDCOMP=m
CONFIG_PPP_DEFLATE=m
CONFIG_PPP_FILTER=y
CONFIG_PPP_MPPE=m
CONFIG_PPP_MULTILINK=y
CONFIG_PPPOATM=m
CONFIG_PPPOE=m
CONFIG_PPTP=m
CONFIG_PPPOL2TP=m
CONFIG_PPP_ASYNC=m
CONFIG_PPP_SYNC_TTY=m
```
Note that some of the functionality is built as kernel module, so you might need to load them during runtime before you can use that functionality.
