### ISSUE TITLE
Apparmor Config File

### ISSUE THREAD

**Issue by joinsplit** [fabianishere/pve-edge-kernel#2]
Hello,

Thanks for updating the readme, after finding your repo I tested out 5.7.2 among others, but got stuck with the LXC Apparmor issue.

I followed your instructions to update /etc/apparmor.d/parser.conf, but it did not work successfully. In the end I had to update /etc/apparmor/parser.conf on my Proxmox host to get the apparmor service up an running again. Leaving the originally created /etc/apparmor.d/parser.conf also prevented the apparmor service from starting, so I needed to remove it.

My first github issue, so thanks!

**Comment by fabianishere** [comment]
Hi,

Thank you for the notice! You are indeed right! This was a typo on my part, will update the README!
