### ISSUE TITLE
LXC containers doesn't work with kernel 5.16.x and 5.15.19

### ISSUE THREAD

**Issue by ArnoCtr** [fabianishere/pve-edge-kernel#238]
LXC containers doesn't work with kernel 5.16.x and 5.15.19-2.

As mentionned, apparmor parser file was rolling back to old config.
When start any container with "pct start XXX -debug=1", i obtain this error message.

`
problem with monitor socket, but continuing anyway: got timeout

main: 256 Container is already running
in:256 - Container is already running
`

I have tested with apparmor enabled or disabled.

I use GPU passthrougth on one container and for this my /etc/subgid was modified. Is this the cause of my problem ?

**Comment by Crazyachmed** [comment]
I had the same issue, even after using the original file I backuped. What fixed the issue for me was to use the original parser.conf from the proxmox repo's .deb.

Here you go:

```
# parser.conf is a global AppArmor config file for the apparmor_parser
#
# It can be used to specify the default options for the parser, which
# can then be overriden by options passed on the command line.
#
# Leading whitespace is ignored and lines that begin with # are treated
# as comments.
#
# Config options are specified one per line using the same format as the
# longform command line options (without the preceding --).
#
# If a value is specified twice the last version to appear is used.

## Suppress Warnings
#quiet

## Be verbose
#verbose

## Set additional include path
#Include /etc/apparmor.d/
# or
#Include /usr/share/apparmor


## Set location of apparmor filesystem
#subdomainfs /sys/kernel/security/apparmor

## Set match-string to use - for forcing compiler to treat different kernels
## the same
# match-string "pattern=aadfa audit perms=crwxamlk/ user::other"

## Turn creating/updating of the cache on by default
#write-cache

## Show cache hits
#show-cache

## skip cached policy
#skip-cache

## skip reading cache but allow updating
#skip-read-cache


#### Set Optimizaions.  Multiple Optimizations can be set, one per line ####
# For supported optimizations see
#   apparmor_parser --help=O

## Turn on equivalence classes
#equiv

## Turn off expr tree simplification
#Optimize=no-expr-simplify

## Turn off DFA minimization
#Optimize=no-minimize

## Adjust compression
#Optimize=compress-small
#Optimize=compress-fast

## Pin the policy feature set (avoid regressions when policy is lagging behind
## the kernel)
compile-features=/usr/share/apparmor-features/features

```

**Comment by ArnoCtr** [comment]
@Crazyachmed same issue with original apparmor parser.conf file from repo.

**Comment by ArnoCtr** [comment]
I found the cause of my problem.
A file added by me in the configuration of apparmor.
File removed and issue resolved.

**Comment by fabianishere** [comment]
My apologies. These changes were only meant for v5.16.x, but accidentally slipped into the v5.15.x branch.

See the following comment about this issue: https://github.com/fabianishere/pve-edge-kernel#apparmor-intervention
