### ISSUE TITLE
Support for kernel 5.17?

### ISSUE THREAD

**Issue by Calimerorulez** [fabianishere/pve-edge-kernel#241]
Hi,

I came across your repo and I was wondering how hard it would be for me to compile kernel 5.17. I know it is really bleeding edge, but I would like to use it because I have a Ryzen 5600G Proxmox server running, and the new kernel contains optimalizations for my CPU.

**Comment by fabianishere** [comment]
Hi,

I have tried building the repository against Linux 5.17-rc4 (see #244), but it seems the current ZFS version is not compatible with Linux 5.17.

We might be able to get it working by cherry-picking the patches from https://github.com/openzfs/zfs/pull/12989.

**Comment by cooljimy84** [comment]
just installed 5.16 edge...
OMG THANK YOU !
Also i would be willing to test 5.17 if needed :+1:

**Comment by Calimerorulez** [comment]
Installed OK :)

Thanks @fabianishere and others.
