### ISSUE TITLE
Nginx & sendfile() invalid argument inside lxc

### ISSUE THREAD

**Issue by piexil** [fabianishere/pve-edge-kernel#245]
Looks like using the 5.16 pve edge reintroduces this issue or a similar one when using nginx inside an LXC 
https://github.com/lxc/lxd/issues/8383
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=f8ad8187c3b536ee2b10502a8340c014204a1af0

I do not know exactly when this was introduced or if it affects earlier versions, I just noticed it on a low traffic website. 

I'm not sure if the issue is with LXC or upstream with the kernel, I also am using 4K aligned SSDs which may be a problem however setting nginx's direct alignment to use 4k blocks didn't fix it. 

As a workaround, you can set sendfile off in nginx conf.

**Comment by fabianishere** [comment]
I believe this patch is already in linux-stable. Let me know if you can still reproduce the issue, then I'll re-open the issue again.
