### ISSUE TITLE
ZFS submodule fix breaks unauthenticated access

### ISSUE THREAD

**Issue by amoiseiev** [fabianishere/pve-edge-kernel#255]
The change made in 5.16 branch to fix zfs submodule breaks unauthenticated access:

https://github.com/fabianishere/pve-edge-kernel/commit/52ce8c92c839e3b3682ee6c8bde7b9341107a552

Potential option here is to switch to https

**Comment by fabianishere** [comment]
This should fix it: [593f0d2](https://github.com/fabianishere/pve-edge-kernel/commit/593f0d2b9528e0cda07874ff946b319212720f7c)
