### ISSUE TITLE
ZFS 2.1.4 pls

### ISSUE THREAD

**Issue by Xaekai** [fabianishere/pve-edge-kernel#261]
ZFS has pushed another new release which provides fixes for some critical bugs, including one that can cause application crashes and system lockup (https://github.com/openzfs/zfs/pull/13234), that crept into 2.1.3.

**Comment by fabianishere** [comment]
Thanks for the heads up! I'll try to push an update ASAP

**Comment by Xaekai** [comment]
Thanks for all you do.
