### ISSUE TITLE
Question: Is br_netfilter kernel feature supported?

### ISSUE THREAD

**Issue by iWangJiaxiang** [fabianishere/pve-edge-kernel#28]
Hi Fabian, I have run into this issue [Missing br_netfilter module | Proxmox Support Forum](https://forum.proxmox.com/threads/missing-br_netfilter-module.53791/) when I tried to run K3S within LXC container.

It seems the fix of this issue is too slow to wait. I want to try you custom kernel to continue LXC K3S plan. Do you think it's gonna work?

**Comment by fabianishere** [comment]
Hi Wang,

As far as I can tell, `br_netfilter` works from within the host and within an LXC container. I would suggest just installing one of the kernel releases of this project on your host and verify whether K3s works with it.

**Comment by iWangJiaxiang** [comment]
Thank you, I'll try it out ASAP 😄
