### ISSUE TITLE
Regular Crashes

### ISSUE THREAD

**Issue by tfs** [fabianishere/pve-edge-kernel#283]
Hi,

with https://github.com/fabianishere/pve-edge-kernel/releases/tag/v5.17.14-1 I get frequent reboots - about every hour - and services (lxc containers) are not starting (hanging).
I'm still looking for more and better error logs. 

Anyone else having this problem?
(I know and apologize for the sparse information - I'm off site and since the machines are headless investigation into the causes or even the specific errors are slow. I'm currently working to roll back to a previous release.)

**Comment by fabianishere** [comment]
Are LXC containers not starting at all?

**Comment by tfs** [comment]
It seems the first LXC start "blocks" - i.e. the unit exits with error. Stopping or starting the service has no effect.
Proxmox UI is not functional unfortunately, too...

**Comment by tfs** [comment]
> Hmm, I am not able to reproduce this myself on v5.17.14-1. Would you be able to share the full log? (e.g., `journalctl -b` or `dmesg`)

Here's the journalctl -b output.
[log.txt.zip](https://github.com/fabianishere/pve-edge-kernel/files/8897362/log.txt.zip)

**Comment by fabianishere** [comment]
Looks like the machine is unable to establish a cluster quorum, which causes the Proxmox filesystem to be unavailable. That in turn explains LXC blocking, since it is trying to access the Proxmox filesystem.

Some log entries that might provide a clue:
> pbs.adaptiveweb.home: error fetching datastores - 500 Can't connect to 192.168.1.6:8007 (No route to host)
> can't mcast to group  state:0, error:12

Any idea why you are getting these network errors? I saw some log entries about `NetworkManager`, does that work with Proxmox?

**Comment by tfs** [comment]
well, this is a small 4 node cluster. 3 are running 5.17.14-1 and are constantly rebooting, thus quorum is hard to achieve. 

.6 is a test installation of PBS inside of one of these - bad pattern, I know.

**Comment by tfs** [comment]
Still no good idea if 5.17.14 was responsible - I rolled back to a pve kernel and random restarts stopped. But I have no correlation or root cause in the logs. For now lets close this as there is nothing to do.
