### ISSUE TITLE
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead

### ISSUE THREAD

**Issue by marcosscriven** [fabianishere/pve-edge-kernel#291]
Following the instructions on readme (on Proxmox 7.2 / 5.15), we get a warning:

`Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).`

Should the instructions be updated to use that instead?

**Comment by fabianishere** [comment]
Thanks for letting me know. I think the proper way to do it now is described [here](https://stackoverflow.com/questions/68992799/warning-apt-key-is-deprecated-manage-keyring-files-in-trusted-gpg-d-instead).
