### ISSUE TITLE
Error on installing 5.18

### ISSUE THREAD

**Issue by Calimerorulez** [fabianishere/pve-edge-kernel#292]
Hi @fabianishere 

I'm trying to upgrade from 5.17 to 5.18, but on installing pve-kernel-5.18-edge, the following error is thrown:

`dkms: running auto installation service for kernel 5.18.10-edge:Error! Your kernel headers for kernel 5.18.10-edge cannot be found.
Please install the linux-headers-5.18.10-edge package`

I can't seem to find linux-headers-5.18.10-edge either :)

Please help; thanks again!

**Comment by fabianishere** [comment]
You should use `pve-headers-5.18-edge` to install the kernel headers.
