### ISSUE TITLE
Question: Linux 5.10

### ISSUE THREAD

**Issue by twinrix1** [fabianishere/pve-edge-kernel#30]
Hi,

any timeline on updating to Linux 5.10?

Thanks

**Comment by fabianishere** [comment]
Hi,

Thank you for the question. I have been a little busy with other things, as well as upgrading the build server. 
I expect it will be ready next week. The update to Linux 5.10 will follow soon after.

**Comment by fabianishere** [comment]
I just released Linux 5.10.9!
