### ISSUE TITLE
Upstream Patches

### ISSUE THREAD

**Issue by edcarroll** [fabianishere/pve-edge-kernel#303]
Have been using your builds for a while now, and it's been great!

I have had one issue though, detailed in [this proxmox forum thread](https://forum.proxmox.com/threads/vm-shutdown-kvm-entry-failed-hardware-error-0x80000021.109410/). It appears to have been resolved in the latest 5.15 kernel via some patches, and I wondered if they could be applied here as well please? [The original commit was here I think](https://github.com/proxmox/pve-kernel/commit/f6df304f26cc1231a3109fe1f8f383d5c418e71d).

I'm running the very latest 5.19 and still seeing the issue reproduced, so it seems to not have been fixed in the kernel itself.

Many thanks!

**Comment by fabianishere** [comment]
Thanks for letting me know! I'll try to import the patches this week.

**Comment by edcarroll** [comment]
Fantastic, thank you for sorting this!
