### ISSUE TITLE
LXC is not available

### ISSUE THREAD

**Issue by xoomp** [fabianishere/pve-edge-kernel#31]
GPU pass-through runs stably for 3 months, except lxc can’t be used，kernel 5.8.

**Comment by fabianishere** [comment]
Hi,

Could you post the output of `journalctl` after trying to start an LXC container? I suspect it might be related to [AppArmor not working by default in Proxmox with these new kernels](https://github.com/fabianishere/pve-edge-kernel#apparmor-issues).

**Comment by fabianishere** [comment]
I will close this issue for now. Let me know if the above instructions still don't resolve your issue.
