### ISSUE TITLE
i2c i2c-6: sendbytes: NAK bailout.

### ISSUE THREAD

**Issue by HolgerHuo** [fabianishere/pve-edge-kernel#313]
Hi! Thanks for providing these edge kernels!

I've recently upgraded my PVE from stock 5.15 kernel to latest `5.19.4` and found my kern.log filled with `i2c i2c-6: sendbytes: NAK bailout`. I've done some searching and found out that this device is part of my Intel IGD and this error won't be thrown when there is an external monitor connected via HDMI, and it will again start showing up the second i remove the cable. However, this never happened before upgrading. Is there anything that I should tweak to tackle this error?

The following is the entry for `i2c-6` by `i2cdetect`:
`i2c-6   i2c             i915 gmbus dpb                          I2C adapter`

I'm using an Intel N5105 nuc with Intel JasperLake [UHD Graphics].

**Comment by fabianishere** [comment]
I expect this to be a regression. You should probably report this with the upstream driver developers.

**Comment by HolgerHuo** [comment]
Ok. This seems to be an occasional case as many other n5105(same hardware) users did not report this using the same kernel. I'll try the latest 5.19.5 tomorrow and report back if the problem persists.

**Comment by HolgerHuo** [comment]
I didnt have any luck with that but it does seem an external issue and I'll check for other resources.

Thanks for your help!
