### ISSUE TITLE
May MGLRU be imported to 5.19 kernel？

### ISSUE THREAD

**Issue by troubadour-hell** [fabianishere/pve-edge-kernel#319]
MGLRU can generally provide better performance on various workloads and various hardware platforms. May it be imported into the 5.19 kernel? It seems that it is easy to apply patch v13 for 5.19. I have added it to my OpenWrt with a 5.19 kernel. Just apply the patch and add config to kconfig. Thanks for your work!

**Comment by fabianishere** [comment]
Hi,

I try to stay as close to PVE upstream as possible and don’t maintain builds with custom patches. However, it should be quite easy to build a kernel with custom patches yourself if you follow the instructions in the README.

**Comment by troubadour-hell** [comment]
Thanks for your reply~
