### ISSUE TITLE
Uninstall instructions in README.md 

### ISSUE THREAD

**Issue by TheLinuxGuy** [fabianishere/pve-edge-kernel#320]
Would it make sense to document the rollback/uninstall instructions in README.md ?

Proxmox just released their own [5.19 kernel](https://forum.proxmox.com/threads/opt-in-linux-5-19-kernel-for-proxmox-ve-7-x-available.115090/#post-498817) as optional this week and `apt remove pve-kernel-5.19-edge` while it did remove some packages the default boot option remains to exist in UEFI menu.

I think `apt-get remove pve-kernel-5.19.9-edge` is one of the necessary steps but it would be nice to have the official word on it.

**Comment by fabianishere** [comment]
I have added the instructions to the README: https://github.com/fabianishere/pve-edge-kernel#removal
