### ISSUE TITLE
Is a meta package for the repository possible?

### ISSUE THREAD

**Issue by piexil** [fabianishere/pve-edge-kernel#338]
Hello! Thank you so much for putting the effort to build newer proxmox kernels - I follow development of the kernel a lot and it's nice not having to wait for proxmox upstreams rather slow updates given new kernels can help with things like vfio quite a bit. 

One problem I have though, is I use ansible playbooks for upgrading my servers with minimal interaction and there's no nice way to have it update the kernel when the version number jumps (e.g. 5.19 -> 6.0). If there was a meta package that always pointed to the latest kernel & header combo this would make this process trivial.

**Comment by fabianishere** [comment]
Hi,

Thanks for the suggestion. However, I prefer not to provide such a package, since upgrades might silently break your system with such a package installed. 

Furthermore, given that major versions are only released every two month, it introduces additional maintenance effort for little gain.

**Comment by piexil** [comment]
Thank you for considering it anyways, I appreciate it!

**Comment by piexil** [comment]
For those interested, heres the ansible playbook 

`---
- hosts: all
  gather_facts: yes
  vars:
    kernel_version: 6.0

  tasks:
    - name: Add pve-kernel-edge gpg
      ansible.builtin.apt_key:
        url: https://dl.cloudsmith.io/public/pve-edge/kernel/gpg.8EC01CCF309B98E7.key
        keyring: /usr/share/keyrings/pve-edge-kernel.gpg

    - name: Add pve-kernel-edge repo
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/pve-edge-kernel.gpg] https://dl.cloudsmith.io/public/pve-edge/kernel/deb/debian bullseye main"
        state: present
        filename: pve-edge-kernel
    - name: Perform a dist-upgrade.
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes


    - name: Update repositories cache and install kernel package
      ansible.builtin.apt:
        pkg: 
         - 'pve-kernel-{{ kernel_version }}-edge'
         - 'pve-headers-{{ kernel_version }}-edge'

        update_cache: yes

    - name: Remove dependencies that are no longer required.
      ansible.builtin.apt:
        autoremove: yes
`
