### ISSUE TITLE
Support for T2 Macs

### ISSUE THREAD

**Issue by AdityaGarg8** [fabianishere/pve-edge-kernel#344]
Hi @fabianishere 

I am a part of the t2linux community (https://t2linux.org/). Recently we’ve been facing requests to get proxmox support for t2 Macs.

Since a lot of patches for the t2 Macs are not yet Mainlined, we provide custom kernels for various distros on this community with has t2 support, and also develop/improve drivers for the same.

Back to the point, I came across your repo, and this one looks amazing for the proxmox users on T2 Macs. Since you actively maintain your repo, could you help us out in getting kernels for the T2 Macs as well?

Thanks
Aditya

**Comment by AdityaGarg8** [comment]
The patches are hosted on the GitHub repo https://github.com/t2linux/linux-t2-patches. The repo also has an extra_config file which contains the extra kernel modules which are to be enabled for the t2 Macs.

**Comment by fabianishere** [comment]
Hi @AdityaGarg8,

Thanks for your interest. I don't have the capacity to maintain a separate patchset right now, but feel free to re-use the tooling in this repository to build a t2 compatible Proxmox kernel. Let me know if I can be of help.
