### ISSUE TITLE
Bpfilter read fail 0

### ISSUE THREAD

**Issue by barzag** [fabianishere/pve-edge-kernel#346]
I solicit your help because I have recently this message with the last kernel v6.0.12

`bpfilter read fail 0`

any ideas ?

**Comment by fabianishere** [comment]
Do you observe any other issues than the log message?

**Comment by barzag** [comment]
I only get this error message

**Comment by barzag** [comment]
any idea where it could come from?

**Comment by fabianishere** [comment]
No, but it expect it is harmless if you are not observing any other errors.

**Comment by amoiseiev** [comment]
It comes from pve-firewall querying iptables that now generates these messages. I believe it has something to do with nftables compatibility.

If you don't use pve-firewall, you can try stopping/disabling/masking it. Not sure what's the downstream impact, if any.
