### ISSUE TITLE
workflows/release: Submodule checkout needed?

### ISSUE THREAD

**Issue by thetredev** [fabianishere/pve-edge-kernel#347]
Line https://github.com/fabianishere/pve-edge-kernel/blob/master/.github/workflows/release.yml#L60 (job `publish`) forces submodule checkout, which I don't think is necessary for the workflow. So I'm guessing this line can be removed.

**Comment by fabianishere** [comment]
You are correct, the submodule checkout is not necessary for the publish job.

**Comment by thetredev** [comment]
Alright, I'll create a PR.
