### ISSUE TITLE
No valid OpenPGP data found

### ISSUE THREAD

**Issue by arthur-morgan-1** [fabianishere/pve-edge-kernel#360]
I get this:

`No valid OpenPGP data found
`
after typing the first command

`
curl -1sLf 'https://dl.cloudsmith.io/public/pve-edge/kernel/gpg.8EC01CCF309B98E7.key' | gpg --dearmor -o /usr/share/keyrings/pve-edge-kernel.gpg`

How can it be solved?

**Comment by fabianishere** [comment]
You should run this command:

```
curl -1sLf 'https://dl.cloudsmith.io/public/pve-edge/kernel/gpg.8EC01CCF309B98E7.key' | gpg --dearmor -o /usr/share/keyrings/pve-edge-kernel.gpg
```

**Comment by arthur-morgan-1** [comment]
Sorry I edited my post, this is the exact same command I'm running (I copy it from the git page instructions) 
And I still get this error message

**Comment by fabianishere** [comment]
Probably the download via `curl` failed. What does the following command give:

```
 curl -1sLf 'https://dl.cloudsmith.io/public/pve-edge/kernel/gpg.8EC01CCF309B98E7.key' 
```

**Comment by arthur-morgan-1** [comment]
It says nothing after this command

**Comment by fabianishere** [comment]
What if you remove the `s` and `f` flags?

**Comment by arthur-morgan-1** [comment]
it says:
`curl: (6) Could not resolve host: dl.cloudsmith.io`

**Comment by fabianishere** [comment]
Your DNS resolver is not resolving `dl.cloudsmith.io`. Perhaps try switching DNS servers.

**Comment by arthur-morgan-1** [comment]
Should I try to change DNS in the router? `8.8.8.8` for example?

**Comment by arthur-morgan-1** [comment]
Same message after changing the router DNS to `8.8.8.8` :(
