### ISSUE TITLE
Builds on Debian 11 are failing

### ISSUE THREAD

**Issue by amoiseiev** [fabianishere/pve-edge-kernel#361]
It looks like GCC 10 (default) is crashing (segmentation fault) trying to compile some drivers, failing the build process. Installing GCC-11 from Debian testing repo solves the issue.

**Comment by fabianishere** [comment]
Thanks for letting me know. My build server is currently down for maintenance so I can't reproduce. Hopefully the issue is fixed when it comes back online. 

I prefer building with the default GCC to prevent any possible ABI conflicts.

**Comment by amoiseiev** [comment]
Yeah, usually you want stock, if you want to stay within the same building env for ABI purposes, you may need to rebuild GCC with a patch (if it exists) or start excluding or patching problematic drivers. Neither is idea. For kernel builds specifically, what's your ABI concern? People trying to build custom modules on their PVE machines?

**Comment by fabianishere** [comment]
Yeah, things potentially breaking in mysterious ways due to us using a newer GCC version than upstream.

**Comment by ThomasLamprecht** [comment]
It's this [Debian bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1027456#40), as a hacky workaround you can revert the patch that confuses GCC 10.2.1-6 from Debian Bullseye, i.e.: apply:
https://git.proxmox.com/?p=pve-kernel.git;a=commitdiff;h=3ba39b6c0ab2db90bbddaa03024b0037edaaddac

An actual workaround would be to backport [this GCC patch](https://gcc.gnu.org/git/gitweb.cgi?p=gcc.git;h=ee15832c53d52656e562c29110f2be1cfb66c450) to that GCC version, or wait until the next Bullseye point release when Debian upstream (hopefully) did so.

FWIW, there's an official [Proxmox VE 6.1 opt-in kernel](https://forum.proxmox.com/threads/opt-in-linux-6-1-kernel-for-proxmox-ve-7-x-available.119483/#post-518444) already.

**Comment by fabianishere** [comment]
@ThomasLamprecht Thanks for pointing that out! I'll probably copy the hacky workaround to get things working in the meantime.

By the way, I am indeed not doing any releases for Linux 6.1 since you guys already beat me to it 😄

**Comment by fabianishere** [comment]
Implemented the workaround, so builds should work again now.
