### ISSUE TITLE
Arm64 build support

### ISSUE THREAD

**Issue by jiangcuo** [fabianishere/pve-edge-kernel#363]
debian/rules.d/arch/arm64.mk
```
KERNEL_BUILD_ARCH	= arm64
KERNEL_HEADER_ARCH	= $(KERNEL_BUILD_ARCH)
KERNEL_BUILD_IMAGE	= Image
KERNEL_IMAGE_PATH	= arch/$(KERNEL_BUILD_ARCH)/boot/${KERNEL_BUILD_IMAGE}
KERNEL_INSTALL_FILE	= vmlinuz
````
I use the arm version of the edge kernel and have been testing it for 3 months. It performs very well.

**Comment by fabianishere** [comment]
Thanks! I added the file in [0ffeef0](https://github.com/fabianishere/pve-edge-kernel/commit/0ffeef0c25226497f30e141e44477ab7522f79da)
[now](https://github.com/fabianishere/pve-edge-kernel/commit/0ffeef0c25226497f30e141e44477ab7522f79da)
