### ISSUE TITLE
About upgrading to Linux kernel 6.3

### ISSUE THREAD

**Issue by kyocooro** [fabianishere/pve-edge-kernel#366]
Linux kernel 6.3 RC1 was released on March 6th, 2023 by Linus Torvalds.

Do you have any plan to update pve-edge-kernel to 6.3?

Sorry for bothering you

**Comment by fabianishere** [comment]
I usually only publish stable (non-RC) releases unless there’s a strong demand for it. However, I must admit that I haven’t yet had the time to add a Linux 6.2 branch.

**Comment by davidcoulson** [comment]
Is there an ETA for providing a 6.2 kernel release?

**Comment by fabianishere** [comment]
@davidcoulson There is already a Linux 6.2 kernel provided by Proxmox if you need it.

**Comment by davidcoulson** [comment]
> @davidcoulson There is already a Linux 6.2 kernel provided by Proxmox if you need it.

For some reason the 'official' proxmox 6.x kernels won't boot on my system (hangs with "EFI Stub: loaded initrd from command line option"), but the 6.0-edge ones work fine. Haven't figured out if it is related to kernel config differences or patches.

**Comment by floco** [comment]
Hello @fabianishere 
Thanks a lot for all your work on this repo :-)
It would be great to have a 6.2.x edge kernel so [AdityaGarg8](https://github.com/AdityaGarg8) can generate a T2 patched kernel for proxmox 8 on mac intel. Is that something you could consider in the future ?

**Comment by fabianishere** [comment]
@floco Have a look at Proxmox’s kernel sources, they are already at Linux 6.2, so you can rebase on top of that: https://github.com/proxmox/pve-kernel

**Comment by floco** [comment]
Thanks @fabianishere for the super fast reply :-)
The official proxmox link was proposed in there: https://github.com/AdityaGarg8/pve-edge-kernel-t2/issues/1
But looks to be a problem for @AdityaGarg8 to use that one due to the lack of building instructions and repos differences.
