### ISSUE TITLE
Linux 6.1.22 LTS released

### ISSUE THREAD

**Issue by dreamdenizen** [fabianishere/pve-edge-kernel#367]
First off, thanks for what you do! 

Looks like like 6.1 was announced as LTS, with 6.1.22 dropping a couple of days ago. Will there be support for it here?

**Comment by fabianishere** [comment]
Hi,

Usually I only maintain kernel versions ahead of the available Proxmox kernels (unless there is a strong use-case). I believe Proxmox offers both Linux 6.1 and 6.2 at the moment, so I expect the next `pve-edge-kernel` release to be Linux 6.3.

**Comment by dreamdenizen** [comment]
Hi Fabian, thanks for the reply. I'm new to ProxMox, but learning quickly. Thanks for letting me know!
