### ISSUE TITLE
Continued support for 5.15 and 6.1 ？

### ISSUE THREAD

**Issue by jiangcuo** [fabianishere/pve-edge-kernel#371]
Hello ,

Proxmox VE 8.1 uses the 6.5 kernel, but the 6.5 kernel is already eol.
I don't  understand their kernel update roadmap.

5.15 and 6.1 are the LTS versions that we can run very well, such as zfs and nvidia-vgpu.
Because of the 2.0 update of ZFS, there will be compatibility issues when degrade to the 5.15 kernel  on pve version 8.X(5.15 use zfs-2.1.x).

We can see  some kernel issue  in proxmox-ve raodmap. 

Are you interested in keeping updates to 5.15 and 6.1?

**Comment by fabianishere** [comment]
Hello @jiangcuo, I’m not planning to create further releases for 5.15 and 6.1. This repository is mostly aimed at running mainline kernels on Proxmox.

Though, as long as you backport the Proxmox-specific patches, it should be doable to keep building those kernels using this repository.
