### ISSUE TITLE
Coffee Lake ER crashes

### ISSUE THREAD

**Issue by reedog117** [fabianishere/pve-edge-kernel#4]
Trying these kernels with a Coffee Lake ER Xeon processor (Xeon E-2276G) and getting a bunch of random kernel panics related to gvt. Should I be using the generic kernel or should I try the Cascade Lake kernel?

**Comment by fabianishere** [comment]
Hi Patrick,

The Coffee Lake and Cascade Lake microarchitectures do not have exactly the same instruction set  (I believe AVX512 is missing from Coffee Lake). Given that I do not have Coffee Lake builds (yet), I indeed recommend you use the generic kernel.

Let me know if your issues persist. :)
