### ISSUE TITLE
Could you create a generic with the Navi Reset Patch included?

### ISSUE THREAD

**Issue by dotprofile** [fabianishere/pve-edge-kernel#5]
With some amd video cards, they need to be reset via a nonstandard method in order to work with PCI pass through. A generic image would be wonderful. 

https://github.com/gnif/linux/commit/e3bb0b3ad209004eeac48fceeff148840080d4ee

Forum post: https://forum.level1techs.com/t/navi-reset-kernel-patch/147547/47

https://del.dog/Navipatch.txt

**Comment by fabianishere** [comment]
Yes, I can create one with this patch. Do you have a preference for a particular kernel version?

**Comment by fabiosun** [comment]
Hi Fabian and thank you for all of these kernel.
Could you include this Navi patch on this one:
https://github.com/fabianishere/pve-edge-kernel/releases/download/v5.7.8/pve-edge-kernel-5.7.8-1-zen2_5.7.8-1_amd64.deb
Thank you

**Comment by fabianishere** [comment]
Hi, these kernels should be coming in anytime soon now. Could you verify whether they work correctly?

**Comment by fabiosun** [comment]
Hi, personally I cant because I have a Nvidia card
but many users that are following my Proxmox/OSX guide can test

**Comment by fabianishere** [comment]
Will close this for now. Let me know if anyone experiences issues regarding the Navi Patch flavor.

**Comment by VNGXR** [comment]
So these **navi-reset** builds are generic, not Zen 2 / Cascade Lake?

**Comment by fabianishere** [comment]
Correct! The generic builds should run on most systems.
