### ISSUE TITLE
Add patch option for bridge forwarding mask

### ISSUE THREAD

**Issue by markh0338** [fabianishere/pve-edge-kernel#58]
There is a niche group of network engineers that use Proxmox and Eve-NG in an lxc container. For this to work properly, we need to patch the kernel with a specific bridge patch. I will attach the patch and some links with additional information. This patch can be dropped into the pve patches directory and should work fine. 

https://lists.linuxfoundation.org/pipermail/bridge/2015-January/009291.html
https://interestingtraffic.nl/2017/11/21/an-oddly-specific-post-about-group_fwd_mask/
[br_fwd_grp_mask.patch.zip](https://github.com/fabianishere/pve-edge-kernel/files/6053684/br_fwd_grp_mask.patch.zip)

**Comment by fabianishere** [comment]
Hi Mark, 

Thank you for your request. I am currently making some changes to the build process. After that is finished, I’ll consider adding the patch to the repository.

I have looked at the patch and the response from the kernel maintainers. They propose a workaround using `tc-mirred`: https://lists.linuxfoundation.org/pipermail/bridge/2018-October/011238.html. Is that sufficient for your use-case?

In the meantime, if others are also interested in this patch, please let me know, as to give me an idea of the general interest in this patch.

**Comment by markh0338** [comment]
Hi Fabian,
That method may work but we are reliant on the way an application behaves and not a configuration we can make on our own. For the last few months I've been using your build process, adding this patch and using it in my lab and it works great. I was planning on automating this in GitHub but figured I would reach out since you've already got that figured out. Thanks for the consideration.

**Comment by jvoss** [comment]
Hi Fabian,

Just adding a comment for my vote to support this kernel patch.

I know you're changing your build process but would it help if someone submitted a PR?

**Comment by fabianishere** [comment]
Hi @jvoss,

Thank you for showing interest. You could add the patch to one of the branches, but a lot of files have moved around, so it'll probably require a rebase. However, it would allow you to build the kernel yourself for the time being.

**Comment by fabianishere** [comment]
Unfortunately, I have decided to not pickup your request at this time. The effort required to maintain a separate set of builds for this feature is unfortunately too much considering the small amount of users for these builds.

As alternative, you could periodically build a kernel with these patches applied yourself. If you need help with that, feel free to comment on this issue.
