### ISSUE TITLE
When should we expect 5.8.x kernel releases?

### ISSUE THREAD

**Issue by reedog117** [fabianishere/pve-edge-kernel#6]
Just wondering when to expect 5.8.x kernel releases.

**Comment by fabianishere** [comment]
Hi Patrick, I am currently on vacation so there might be some delays. :)

Last time I looked at Linux 5.8, OpenZFS did not build on it. However this might have changed in the meantime.

**Comment by fabianishere** [comment]
I have released Linux 5.8 kernels with ZFS 0.8.4 backported.
