### ISSUE TITLE
can you add slhc and ppp_generic module?

### ISSUE THREAD

**Issue by skill7899** [fabianishere/pve-edge-kernel#7]
i run openwrt in lxc, and use pppoe ,but not work,because the host pve kernel not found slhc.ko and ppp_generice.ko，can you compile its into pve kernel。i try to compile ,but fail 。thank you。

**Comment by fabianishere** [comment]
Hi,

I don’t think the best approach for this use case is to build a custom kernel. Instead, I would suggest using DKMS to load additional kernel modules dynamically.

**Comment by skill7899** [comment]
ok
