### ISSUE TITLE
Question: Testing OpenZFS 2.0.0-rc1

### ISSUE THREAD

**Issue by joinsplit** [fabianishere/pve-edge-kernel#8]
Hello,

Is it possible at all to build a recent kernel with the latest rc1 of OpenZFS 2.0? I see there is a pre release up & would be interested in testing it.

Thanks as always!

**Comment by fabianishere** [comment]
Hi,

Given that I track the [zfsonlinux repository](https://git.proxmox.com/?p=zfsonlinux.git;a=summary) from Proxmox, this is a bit more difficult. Perhaps I can try to put the entire release into a patch on top of 0.8.4.

**Comment by joinsplit** [comment]
Hello - I think it will just be easiest to wait on the proxmox repo & save the trouble. Thanks!

**Comment by joinsplit** [comment]
Hello again, on this point, i see 0.85-pve1 available on git.proxmox.com, would it be possible to get this into the next edge kernel release?

**Comment by fabianishere** [comment]
@joinsplit Thanks for the notice, will update ZFS in the next release.

**Comment by fabianishere** [comment]
I have updated to ZFS 2.0.1 via the Proxmox upstream.

**Comment by mac-linux-free** [comment]
How can I update to ZFS 2.0.1 via Proxmox upstream?

**Comment by fabianishere** [comment]
You'll need to build it yourself for now. See: https://git.proxmox.com/?p=zfsonlinux.git;a=summary

**Comment by mac-linux-free** [comment]
ok I am testing
